config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: 'home#index'
    resources :categories
    resources :products
    resources :orders, only: %i[index update show destroy]
    resources :users, only: %i[index update show destroy] do
      member do
        get :toggle_status
      end
    end
  end
  root to: 'home#index'
  devise_for :users
  resources :orders, only: %i[index new create show]
  resources :products, only: %i[index show]
  resources :checkout, only: %i[] do
    collection do
      get :cancel
      get :success
      get '', action: :new
    end
  end

  resources :carts, only: %i[index create destroy] do
    member do
      get :increment
      get :decrement
    end
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    belongs_to :product
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_cart, only: %i[destroy increment decrement]

  def index
    @carts = current_user.carts.select('carts.*, products.name, products.price').joins(:product).all
  end

  def create
    cart = current_user.carts.find_by_product_id(params[:product_id])

    if cart
      cart.increment!(:qt)
    else
      cart = current_user.carts.create!(product_id: params[:product_id], qt: 1)
    end

    respond_to do |format|
      format.html { redirect_to root_path, notice: 'تمت الاضافة للسلة' }
      format.json { render json: { status: :ok, cart: cart } }
    end
  end

  def destroy
    @cart.destroy

    respond_to do |format|
      format.json { render json: { status: :ok, cart: @cart } }
      format.any { redirect_to carts_path, notice: 'تم حذف  المنتج من سلة المشتريات' }
    end
  end

  def increment
    @cart.increment!(:qt)
    respond_to do |format|
      format.json { render json: { status: :ok, cart: @cart } }
      format.any { redirect_to carts_path, notice: 'تم تحديث السلة' }
    end
  end

  def decrement
    @cart.decrement!(:qt)
    @cart.destroy unless @cart.qt.positive?

    respond_to do |format|
      format.json { render json: { status: :ok, cart: @cart } }
      format.any { redirect_to carts_path, notice: 'تم تحديث السلة' }
    end
  end

  private

  def set_cart
    @cart = current_user.carts.find_by_product_id(params[:id])
    puts "@cart: #{@cart}"
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_new.html.erb
<%= form_with url: carts_path do |f| %>
    <%= f.hidden_field :product_id, value: product.id %>
    <%= f.button 'اضافة للسلة', type: 'submit', class: 'btn btn-primary btn-sm shadow-none' %>
<% end %>

app/views/carts/index.html.erb
<h3 class="mb-4">سلة المشتريات</h3>

<% @carts.each do |cart| %>
  <%= render 'products/product', product: cart.product do %>
      <div>
          <%= link_to '-', decrement_cart_path(cart.product_id), class: 'btn btn-seconary shadow-none' %>
          <strong><%= cart.qt %></strong>
          <%= link_to '+', increment_cart_path(cart.product_id), class: 'btn btn-seconary shadow-none' %>
          <%= link_to 'حذف', cart_path(cart.product_id), method: :delete, data: { confirm: 'هل أنت متأكد؟' }, class: 'btn btn-danger btn-sm shadow-none ps-3' %>
        </div>
  <% end %>
<% end %>

<% if @carts.size.positive? %>
<div class="bg-white p-2 my-3 d-flex justify-content-between align-items-center">
  <strong>المجموع : <span dir="ltr"><%= number_to_currency(@carts.sum { |item| item.price * item.qt }) %></span></strong>
  <%= link_to 'متابعة للدفع', '/checkout', class: 'btn btn-primary btn-lg shadow-none' %>
</div>
<% else %>
<div class="text-center text-muted">سلة المشتريات فارغة</div>
<% end %>