config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: 'home#index'
    resources :categories
    resources :products
    resources :orders, only: %i[index update show destroy]
    resources :users, only: %i[index update show destroy] do
      member do
        get :toggle_status
      end
    end
  end
  root to: 'home#index'
  devise_for :users
  resources :orders, only: %i[index new create show]
  resources :products, only: %i[index show]
  resources :checkout, only: %i[] do
    collection do
      get :cancel
      get :success
      get '', action: :new
    end
  end

  resources :carts, only: %i[index create destroy] do
    member do
      get :increment
      get :decrement
    end
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html dir="rtl" lang="ar">
  <head>
    <title>Cell Fashions - لوحة التحكم</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'admin', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="<%= admin_root_path %>">Admin</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link <%= active_page_class('admin/home') %>" href="<%= admin_root_path %>">الرئيسية</a>
            </li>
            <li class="nav-item">
              <a class="nav-link <%= active_page_class('admin/orders') %>" href="<%= admin_orders_path %>">الطلبات</a>
            </li>
            <li class="nav-item">
              <a class="nav-link <%= active_page_class('admin/categories') %>" href="<%= admin_categories_path %>">الأقسام</a>
            </li>
            <li class="nav-item">
              <a class="nav-link <%= active_page_class('admin/products') %>" href="<%= admin_products_path %>">المنتجات</a>
            </li>
            <li class="nav-item">
              <a class="nav-link <%= active_page_class('admin/users') %>" href="<%= admin_users_path %>">المستخدمين</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container py-3">
      <%= alert_notice %>
      <%= alert_success %>
      <%= alert_alert %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html dir="rtl" lang="ar">
  <head>
    <title>CellFashions</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
       <div class="col-md-8 mx-auto py-4">
         <div class="text-center">
           <a href="<%= root_path %>"><%= image_tag "logo.png", width: 170 %></a>
         </div>
         <ul class="justify-content-center my-4 nav">
          <li class="nav-item">
            <a class="nav-link nav-link text-dark <%= active_page_class 'home' %>" href="<%= root_path %>">الرئيسية</a>
          </li>
          <li class="nav-item">
            <%= link_to "سلة المشتريات(#{current_user&.carts&.count || 0})", carts_path, class: "nav-link text-dark #{active_page_class 'carts'}" %>
          </li>
          <li class="nav-item">
            <%= link_to 'طلباتي', orders_path, class: "nav-link text-dark #{active_page_class 'orders'}" %>
          </li>
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'تسجيل الخروج', destroy_user_session_path, class: "nav-link text-dark", method: :delete, data: { confirm: 'هل أنت متأكد من تسجيل الخروج؟' } %>
          </li>
          <% end %>
        </ul>
        <%= alert_notice %>
        <%= alert_success %>
        <%= alert_alert %>
        <%= yield %>
       </div>
    </div>
  </body>
</html>